server:
  port: 9001
employee:
  greeting: Welcome to Local Employee Register
spring:
  profiles:
    active: testdata
  application:
    name: employee-register
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888