server:
  port: 9001
employee:
  greeting: Welcome to Config Store Employee Register
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee-register-db
    username: admin
    password: admin
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5